### ISSUE TITLE
Question: how to access two entities which start with same alphabet

### ISSUE THREAD

**Issue by SiddiquiImran** [SpoonX/wetland-tutorial#1]
Hi,
How i can access two different entities which start with same character like:

1. BankUser
2. BankingClients

**Comment by RWOverdijk** [comment]
I don't understand your question. The letter has nothing to do with the way the entity gets registered. Could you provide me with an example?

**Comment by SiddiquiImran** [comment]
according to the link https://wetland.spoonx.org/Tutorial/querybuilder.html
it says :
It takes a single arguments, which is the alias to use for this entity in the query. Usually it's enough to use the first character of the entity (lower cased). The example above is u for user

so for entity "user" you have used "u"
so how i can access these entities:

1. BankUser
2. BankingClients

**Comment by RWOverdijk** [comment]
Use a different alias. 

> Usually it's enough to use the first character of the entity

This states it's optional. So you could use alias `bu` and `bc` for example. The alias can be anything you want.

Side note: this issue should be on the [wetland repository](https://github.com/SpoonX/wetland)
