### ISSUE TITLE
Question: If I already have tables with foreign key joins how i can use relations?

### ISSUE THREAD

**Issue by SiddiquiImran** [SpoonX/wetland-tutorial#2]
https://wetland.spoonx.org/Tutorial/relations.html

**Client Table:**
mapping.forProperty('id').primary().increments();
mapping.field('apiKey', {type: 'string'});
mapping.field('bankingClientId', {type: 'integer'}); // Foreign key of "Bank Client Table"

**Bank Client Table:**
mapping.forProperty('id').primary().increments();
mapping.field('clientId', {type: 'integer'});
mapping.field('clientPassword', {type: 'string'});

so I have this data structure in DB , do I need to use oneToMany relationship ?

**Comment by RWOverdijk** [comment]
You don't need to define fields for foreign keys. 

It's in the docs. https://wetland.spoonx.org/API/mapping.html#manytoone

Again, wrong repository.
