### ISSUE TITLE
Question: How can I add swagger support?

### ISSUE THREAD

**Issue by SiddiquiImran** [SpoonX/wetland-tutorial#3]
I want to add swagger support in my API so how can i do that?

Can i follow this link for the same:
https://blog.cloudboost.io/adding-swagger-to-existing-node-js-project-92a6624b855b

**Comment by RWOverdijk** [comment]
@SiddiquiImran This repository is for the tutorial. Please move this issue to a different repository.

I don't think this has anything to do with wetland either to be honest.
